apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-skaffold-api
  namespace: dotnet-skaffold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-skaffold-api
  template:
    metadata:
      labels:
        app: dotnet-skaffold-api
    spec:
      containers:
        - name: api
          image: ranjithka/dotnet-skaffold-api
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
