# ---
# apiVersion: image.toolkit.fluxcd.io/v1alpha1
# kind: ImageRepository
# metadata:
#   name: app
#   namespace: default
# spec:
#   image: ranjithka/canary
#   interval: 1m0s

# ---
# apiVersion: image.toolkit.fluxcd.io/v1alpha1
# kind: ImagePolicy
# metadata:
#   name: app
#   namespace: default
# spec:
#   imageRepositoryRef:
#     name: app
#   policy:
#     semver:
#       range: '>= 0.0.0 <0.0.1'