---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: app
  namespace: default
spec:
  image: docker.io/ranjithka/canary
  interval: 1m0s
  exclusionList:
    - "^.*\\.sig$"
    - "1.0.2"
    - "1.1.1|1.0.0"
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: default
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app
  namespace: default
spec:
  imageRepositoryRef:
    name: app
    namespace: default
  filterTags:
    pattern: '.*-beta.*'
  policy:
    semver:
      range: '^0.x-0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: app
  namespace: default
spec:
  sourceRef:
    kind: GitRepository
    name: devops
    namespace: default
  interval: 1m0s
  update:
    strategy: Setters
    path: minikube/dev
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxbot
        email: fluxbot@example.com
      messageTemplate: |
        An automated update from FluxBot
        [ci skip]        
    push:
      branch: app-auto
---
### This take priority over beta, no clue why
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app
  namespace: default
spec:
  imageRepositoryRef:
    name: app
    namespace: default
  policy:
    semver:
      range: 0.0.x