---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: app
  namespace: default
spec:
  image: ranjithka/canary
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app
  namespace: default
spec:
  imageRepositoryRef:
    name: app
  policy:
    semver:
      range: 1.0.x