---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: default
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: "4.0.13"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: default
      interval: 10m
  interval: 10m0s
  releaseName: nginx
  values:
    defaultBackend:
      enabled: false
    controller:
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
      ingressClassResource:
        name: dev-nginx
      resources:
        limits:
          cpu: 250m
          memory: 0.5Gi
        requests:
          cpu: 200m
          memory: 200Mi
      containerPort:
        http: 80
        https: 443
      service:
        enabled: true
        type: NodePort
        nodePorts:
          http: 32080
          https: 31443
          tcp:
            2443: 32443
            27017: 31697
    tcp:
      27017: "default/mongo:27017"
