---
apiVersion: v1
kind: Secret
metadata:
  name: discord-url
  namespace: default
stringData:
    address: "https://discord.com/api/webhooks/1068899269949530243/-74HnpqOY-SjjVi408Pv53BmVDHU016x4iKB7PChP9REqF6_XifW3UJ2k04814ahh3cG"  ## This is not available anymore
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord
  namespace: default
spec:
  type: discord
  secretRef:
    name: discord-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: on-call-webapp
  namespace: default
spec:
  summary: "Local cluster"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: HelmChart
      name: '*' 
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'