apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prd-app
  namespace: default
spec:
  chartRef:
    kind: ExternalArtifact
    name: prd-chart
  interval: 1m0s
  releaseName: prd-dev

  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: prd-dev
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: prd-dev
              spec:
                template:
                  spec:
                    tolerations:
                      - key: workload-type
                        operator: Equal
                        value: cluster-services
                        effect: NoSchedule
