---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: devops
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: git-secrets
  url: ssh://git@github.com/ranjith-ka/Devops
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
    !/minikube/
  
---
### Install Nginx Source 
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx