defaultBackend:
  enabled: false
controller:
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  ingressClassResource:
    name: dev-nginx2
  resources:
    limits:
      cpu: 250m
      memory: 0.5Gi
    requests:
      cpu: 200m
      memory: 200Mi
  # autoscaling:
  #   enabled: false
  #   minReplicas: 1
  #   maxReplicas: 7
  #   targetCPUUtilizationPercentage: 70
  #   targetMemoryUtilizationPercentage: 80
  containerPort:
    http: 80
    https: 443
    # special: 2443
  service:
    enabled: true
    type: NodePort
    nodePorts:
      http: 32081
      https: 31444
      tcp:
        2443: 32444
#### Enable this if you have a Mongo controller in the Kube
        27017: 31698
tcp:
  27017: "default/mongo:27017"
