apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: prd
build:
  artifacts:
    - image: ranjithka/prd
      docker:
        dockerfile: Dockerfile.Prd
  local:
    push: true 
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0
    useDockerCLI: true
  tagPolicy:
    gitCommit: {}
deploy:
  kubeContext: kind-k8s
  helm:
    releases:        
      - name: prd-dev
        chartPath: charts/dev
        valuesFiles:
          - minikube/dev/prd.yaml
        version: 1.0.3
---
apiVersion: skaffold/v4beta10
kind: Config
requires:
  - configs: ["prd"]
metadata:
  name: canary      
build:
  artifacts:
    - image: ranjithka/canary
      docker:
        dockerfile: Dockerfile.Canary
  local:
    push: true
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0
    useDockerCLI: true
  tagPolicy:
    gitCommit: {}
deploy:
  kubeContext: kind-k8s
  helm:
    releases:
      - name: canary-dev
        chartPath: charts/dev
        valuesFiles:
          - minikube/dev/canary.yaml
        version: 1.0.3