apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: devops
build:
  artifacts:
    - image: ranjithka/prd
      kaniko:
        cache: {} # Enable Kaniko cache
        # Optionally specify a remote cache repo:
        # cache:
        #   repo: gcr.io/<your-project>/kaniko-cache
  cluster:
    dockerConfig:
      path: ~/.docker/config.json
  tagPolicy:
    gitCommit: {} # Use the git commit sha as the tag
manifests:
  kustomize:
    paths:
      - minikube/kustomize/base
deploy:
  helm:
    releases:        
      - name: dev
        chartPath: charts/dev
        valuesFiles:
          - minikube/dev/prd.yaml
        version: 1.0.2
# profiles:
#   - name: production  
#     manifests:
#       kustomize:
#         paths:
#           - minikube/kustomize/production
#   - name: staging
#     manifests:
#       kustomize:
#         paths:
#           - minikube/kustomize/staging