apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: prd
portForward:
  - resourceType: service
    resourceName: prd-dev
    port: 8080
    localPort: 8080
    namespace: default
build:
  tagPolicy:
    gitCommit: {}
  # tagPolicy:
  #   envTemplate:
  #     template: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
  artifacts:
    - image: ranjithka/prd
      docker:
        dockerfile: Dockerfile.Prd
        secrets:
          - id: mysecret
            env: USER
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0
    useDockerCLI: true
deploy:
  kubeContext: kind-k8s
  helm:
    releases:        
      - name: prd-dev
        chartPath: charts/dev
        valuesFiles:
          - minikube/dev/prd.yaml
        version: 1.0.3
profiles:
  - name: prd
    activation:
      - env: APP=Production
      - kubeContext: kind-k8s
        command: build
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile.Prd 
---
apiVersion: skaffold/v4beta10
kind: Config
requires:
  - configs: ["prd"]
    activeProfiles:
      - name: profile1
        activatedBy: [profile2]
metadata:
  name: canary
portForward:
  - resourceType: service
    resourceName: canary-dev
    port: 8080
    localPort: 8081
    namespace: default
build:
  artifacts:
    - image: ranjithka/canary
      docker:
        dockerfile: Dockerfile.Canary
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0
    useDockerCLI: true
  tagPolicy:
    gitCommit: {}
deploy:
  kubeContext: kind-k8s
  helm:
    releases:
      - name: canary-dev
        chartPath: charts/dev
        valuesFiles:
          - minikube/dev/canary.yaml
        version: 1.0.3
profiles:
  - name: canary