alertmanager:
  enabled: false

kubeProxy:
  enabled: false

prometheus:
  ingress:
    enabled: true
    ingressClassName: dev-nginx
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
      nginx.ingress.kubernetes.io/http2-push-preload: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 8k
      nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hostname: master.example.com
    path: /
    pathType: Prefix

  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
        jobList:
          - job_name: 'blackbox-external-targets'
            metrics_path: /probe
            params:
              module: [http_2xx]
            static_configs:
              - targets:
                - https://www.google.com
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: prometheus-kube-prometheus-blackbox-exporter:19115

blackboxExporter:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/probe: "true"
  startupProbe:
    enabled: true