## This version is for kind v0.19.0  // https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b
  - role: worker
    extraPortMappings:
      - containerPort: 32081
        hostPort: 8080
        protocol: tcp
      - containerPort: 32444
        hostPort: 1443
      - containerPort: 31444
        hostPort: 143
      - containerPort: 31698
        hostPort: 57017
      - containerPort: 31698
        hostPort: 9093
    image: kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b