---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-metadata-deps
  namespace: default
spec:
  chart:
    spec:
      chart: openmetadata-dependencies
      version: 1.0.5
      sourceRef:
        kind: HelmRepository
        name: open-metadata
        namespace: default
      interval: 10m
  interval: 10m0s
  releaseName: openmetadata-dependencies
  values:
    mysql:
      primary:
        persistence:
          size: 20Gi
        resources:
          requests:
            cpu: "100m"
            memory: "256M"
          limits:
            cpu: "1000m"
            memory: "1024M"

    elasticsearch:
      resources:
        requests:
          cpu: "100m"
          memory: "256M"
        limits:
          cpu: "1000m"
          memory: "1024M"
    airflow:
      enabled: true
      dags:
        persistence:
          enabled: false
      logs:
        persistence:
          enabled: false
      airflow:
        config:
          AIRFLOW__WEBSERVER__BASE_URL: "http://open-metadata-dag.example.com"
        dbMigrations:
          resources:
            requests:
              cpu: "100m"
              memory: "256M"
            limits:
              cpu: "400m"
              memory: "1024M"
        sync:
          resources:
            requests:
              cpu: "100m"
              memory: "256M"
            limits:
              cpu: "400m"
              memory: "1024M"
      triggerer:
        enabled: true
        resources:
          requests:
            cpu: "100m"
            memory: "256M"
          limits:
            cpu: "400m"
            memory: "1024M"
      web:
        resources:
          requests:
            cpu: "200m"
            memory: "256M"
          limits:
            cpu: "400m"
            memory: "1024M"
      ingress:
        enabled: true
        web:
          ingressClassName: dev-nginx
          path: ""
          host: "open-metadata-dag.example.com"
          annotations:
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
            nginx.ingress.kubernetes.io/http2-push-preload: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: 10k
            nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
            nginx.ingress.kubernetes.io/proxy-buffering: "on"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
            nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      scheduler:
        resources:
          requests:
            cpu: "100m"
            memory: "256M"
          limits:
            cpu: "400m"
            memory: "1024M"
---
### Docs
### https://github.com/open-metadata/openmetadata-helm-charts/blob/main/charts/openmetadata/values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-metadata
  namespace: default
spec:
  chart:
    spec:
      chart: openmetadata
      version: 1.0.5
      sourceRef:
        kind: HelmRepository
        name: open-metadata
        namespace: default
      interval: 10m
  interval: 10m0s
  releaseName: openmetadata
  values:
    global: 
      airflow:
        enabled: true
      pipelineServiceClientConfig:
        apiEndpoint: http://openmetadata-dependencies-web.default.svc.cluster.local:8080
    resources:
      requests:
        cpu: "100m"
        memory: "256M"
      limits:
        cpu: "1000m"
        memory: "1024M"
    ingress:
      enabled: true
      className: dev-nginx
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
        nginx.ingress.kubernetes.io/http2-push-preload: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 10k
        nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
        nginx.ingress.kubernetes.io/proxy-buffering: "on"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
        nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - host: open-metadata.example.com
          paths:
            - path: /
              pathType: Prefix