---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: helloworld
  namespace: flux-system
spec:
  image: particule/helloworld
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: helloworld
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: helloworld
  policy:
    semver:
      range: '>= 1.0.0 <2.0.0'