---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prd-app
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/dev
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: devops
        namespace: flux-system
      valuesFiles:
        - ./charts/dev/values.yaml
        - ./minikube/dev/prd.yaml
  interval: 10m0s
  releaseName: prd-dev


  # values:
  #   image:
  #     pullPolicy: Always
  #     tag: 0.0.1
  #   ingress:
  #     annotations:
  #       nginx.ingress.kubernetes.io/enable-cors: "true"
  #       nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
  #       nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  #       nginx.ingress.kubernetes.io/http2-push-preload: "true"
  #       nginx.ingress.kubernetes.io/proxy-body-size: 8k
  #       nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
  #       nginx.ingress.kubernetes.io/proxy-buffering: "on"
  #       nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
  #       nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
  #       nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
  #       nginx.ingress.kubernetes.io/rewrite-target: /$2
  #     enabled: true
  #     hosts:
  #     - host: awesome-http.example.com
  #       paths:
  #       - path: /dev(/|$)(.*)
  #         pathType: Prefix
  #   podAnnotations:
  #     prometheus.io/path: /metrics
  #     prometheus.io/port: "8080"
  #     prometheus.io/scrape: "true"

  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: prd-dev
            spec:
              template:
                spec:
                  tolerations:
                    - key: "workload-type"
                      operator: "Equal"
                      value: "cluster-services"
                      effect: "NoSchedule"