apiVersion: v1
kind: Service
metadata:
  name: jenkinsv2
spec:
  type: NodePort
  ports:
    - port: 8080
      name: jenkinsv2
      nodePort: 30000
      protocol: TCP
  selector:
    name: jenkins
