apiVersion: v1
kind: Namespace
metadata:
  name: kuma-demo
  labels:
    kuma.io/sidecar-injection: enabled
    kuma.io/mesh: ranjithka
---
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: ranjithka
---
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: ranjithka # change to `default` to apply for default mesh
spec:
  mtls:
    enabledBackend: ca-1
    backends:
      - name: ca-1
        type: builtin
        dpCert:
          rotation:
            expiration: 1d
        conf:
          caCert:
            RSAbits: 2048
            expiration: 10y
