### Bump version
### Docs available at https://github.com/anothrNick/github-tag-action
name: Bump version
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: create pre release
      if: |
        github.event_name == 'pull_request'
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: true

    - name: Bump version and push tag
      if: |
        github.head_ref == 'main'
      id: tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        PRERELEASE: false

    - name: Release
      if: steps.tag.outputs.tag
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "${{ steps.tag.outputs.tag }}"