name: Continous Intergration
on:
  pull_request: 
    branches: 
      - main
      - 'releases/**'
  push:
    branches: 
      - main
      - 'releases/**'
      - v[1-9].[0-9]+.[0-9]+-rc.[0-9][0-9][0-9]

  workflow_dispatch:
permissions:
    packages: write
    actions: read
    checks: write
    contents: write
    deployments: read
    id-token: none
    issues: read
    discussions: none
    pages: none
    pull-requests: write
    repository-projects: read
    security-events: write
    statuses: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        run: echo "hi"
        shell: bash