name: reviewdog
on:
 - pull_request
 - push
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1

      # If you want to use the specific version of Go,
      # you need actions/setup-go@v4 action.
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # run staticcheck
      - uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Report all results.
          filter_mode: nofilter
          # Exit with 1 when it find at least one finding.
          fail_on_error: true