name: WSL Testing
on:
 - push
jobs:
  wsl_testing:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v5
        with:
          wsl-shell-command: bash -c "cd && bash --noprofile --norc -euo pipefail '{0}'"
